export interface OrganizationSeedConfig {
  name: string;
  website: string;
  careersPage?: string;
  priority?: number;
  notes?: string;
}

export const DEFAULT_ORGANIZATIONS: OrganizationSeedConfig[] = [
  { name: "1Password", website: "https://1password.com", priority: 10 },
  { name: "360insights", website: "https://360insights.com", careersPage: "https://360insights.com/careers/" },
  { name: "500px", website: "https://500px.com", careersPage: "https://about.500px.com/jobs/" },
  { name: "A Thinking Ape", website: "https://athinkingape.com" },
  { name: "Acerta AI", website: "https://acerta.ai", careersPage: "https://acerta.ai/careers", priority: 10 },
  { name: "Achievers", website: "https://achievers.com", careersPage: "https://www.achievers.com/careers" },
  { name: "Ada", website: "https://ada.cx", priority: 10 },
  { name: "Aislelabs", website: "https://aislelabs.com", careersPage: "https://www.aislelabs.com/careers" },
  { name: "AlayaCare", website: "https://alayacare.com" },
  { name: "Alert Labs", website: "https://alertlabs.com", priority: 10 },
  { name: "Analyze Re", website: "https://analyzere.com", careersPage: "https://analyzere.com/careers" },
  { name: "Applied Brain Research", website: "https://appliedbrainresearch.com" },
  { name: "ApplyBoard", website: "https://applyboard.com", priority: 10 },
  { name: "Arteria AI", website: "https://arteria.ai" },
  { name: "Assent", website: "https://assent.com", careersPage: "https://assent.com/careers" },
  { name: "Attabotics", website: "https://attabotics.com" },
  { name: "Auvik", website: "https://auvik.com" },
  { name: "Awesense", website: "https://awesense.com", careersPage: "https://www.awesense.com/careers" },
  { name: "Axonify", website: "https://axonify.com" },
  { name: "Bench", website: "https://bench.co", careersPage: "https://bench.co/careers" },
  { name: "BenchSci", website: "https://benchsci.com", priority: 10 },
  { name: "Benevity", website: "https://benevity.com", careersPage: "https://www.benevity.com/careers" },
  { name: "BetterSleep", website: "https://bettersleep.com" },
  { name: "BioRender", website: "https://biorender.com", careersPage: "https://www.biorender.com/careers" },
  { name: "BlackBerry", website: "https://blackberry.com", careersPage: "https://www.blackberry.com/us/en/company/careers" },
  { name: "Blue J Legal", website: "https://bluejlegal.com", careersPage: "https://www.bluejlegal.com/careers" },
  { name: "BlueCat", website: "https://bluecatnetworks.com", careersPage: "https://www.bluecatnetworks.com/careers/" },
  { name: "BlueDot", website: "https://bluedot.global" },
  { name: "Bold Commerce", website: "https://boldcommerce.com" },
  { name: "Bonfire", website: "https://gobonfire.com" },
  { name: "Borrowell", website: "https://borrowell.com", priority: 10 },
  { name: "Brim Financial", website: "https://brimfinancial.com" },
  { name: "CAE", website: "https://cae.com", careersPage: "https://www.cae.com/careers/" },
  { name: "Canada Rocket Company", website: "https://canadarocketcompany.com" },
  { name: "Canalyst", website: "https://canalyst.com", careersPage: "https://canalyst.com/careers" },
  { name: "Carbon Engineering", website: "https://carbonengineering.com", careersPage: "https://carbonengineering.com/careers/" },
  { name: "CarbonCure", website: "https://carboncure.com" },
  { name: "Carbonhound", website: "https://carbonhound.io" },
  { name: "Certn", website: "https://certn.co" },
  { name: "ChopValue", website: "https://chopvalue.com" },
  { name: "Clearco", website: "https://clear.co", priority: 10 },
  { name: "ClearEstate", website: "https://clearestate.com", priority: 10 },
  { name: "Clearpath Robotics", website: "https://clearpathrobotics.com", careersPage: "https://clearpathrobotics.com/careers" },
  { name: "Clio", website: "https://clio.com", priority: 10 },
  { name: "Cognito", website: "https://getcognito.ca", careersPage: "https://getcognito.ca/careers" },
  { name: "Cohere", website: "https://cohere.com", priority: 10 },
  { name: "Coinsquare", website: "https://coinsquare.com" },
  { name: "Convictional", website: "https://convictional.com" },
  { name: "Coral", website: "https://coral.ca" },
  { name: "Coveo", website: "https://coveo.com" },
  { name: "CrowdRiff", website: "https://crowdriff.com", careersPage: "https://crowdriff.com/careers" },
  { name: "Cyclica", website: "https://cyclicarx.com", careersPage: "https://cyclicarx.com/careers" },
  { name: "D-Wave Systems", website: "https://dwavesys.com", careersPage: "https://www.dwavesys.com/careers" },
  { name: "D2L", website: "https://d2l.com" },
  { name: "Dapper Labs", website: "https://dapperlabs.com" },
  { name: "DarkVision", website: "https://darkvisiontech.com", careersPage: "https://darkvisiontech.com/careers/" },
  { name: "Deep Genomics", website: "https://deepgenomics.com" },
  { name: "Diagram", website: "https://diagram.vc", careersPage: "https://careers.diagram.ca/companies/diagram-ventures", priority: 10 },
  { name: "Diagram Ventures", website: "https://diagram.ca", careersPage: "https://careers.diagram.ca/companies/diagram-ventures" },
  { name: "Dialogue", website: "https://dialogue.co", priority: 10 },
  { name: "Dooly", website: "https://dooly.ai", careersPage: "https://www.dooly.ai/careers" },
  { name: "Dozr", website: "https://dozr.com" },
  { name: "Drop", website: "https://joindrop.com" },
  { name: "ecobee", website: "https://ecobee.com", priority: 10 },
  { name: "eSentire", website: "https://esentire.com", careersPage: "https://www.esentire.com/company/careers" },
  { name: "EventMobi", website: "https://eventmobi.com" },
  { name: "Fellow", website: "https://fellow.app" },
  { name: "Fiix", website: "https://fiixsoftware.com", careersPage: "https://www.fiixsoftware.com/careers/" },
  { name: "FinanceIT", website: "https://financeit.io", careersPage: "https://www.financeit.io/ca/en/careers" },
  { name: "Flashfood", website: "https://flashfood.com" },
  { name: "Flipp", website: "https://flipp.com", careersPage: "https://corp.flipp.com/careers" },
  { name: "Flinks", website: "https://flinks.com" },
  { name: "Float", website: "https://floatfinancial.com", priority: 10 },
  { name: "Forma.ai", website: "https://forma.ai" },
  { name: "FreshBooks", website: "https://freshbooks.com", priority: 10 },
  { name: "Fullscript", website: "https://fullscript.com", priority: 10 },
  { name: "FundThrough", website: "https://fundthrough.com", careersPage: "https://www.fundthrough.com/careers" },
  { name: "General Fusion", website: "https://generalfusion.com" },
  { name: "Genetec", website: "https://genetec.com", careersPage: "https://www.genetec.com/about-us/careers" },
  { name: "GeoComply", website: "https://geocomply.com" },
  { name: "Geotab", website: "https://geotab.com", careersPage: "https://www.geotab.com/careers/" },
  { name: "GHGSat", website: "https://ghgsat.com", careersPage: "https://www.ghgsat.com/en/jobs" },
  { name: "Helcim", website: "https://helcim.com" },
  { name: "Helpwear", website: "https://helpwear.ca", careersPage: "https://helpwear.ca/careers", priority: 10 },
  { name: "HiMama", website: "https://himama.com", careersPage: "https://jobs.lever.co/himama" },
  { name: "Hootsuite", website: "https://hootsuite.com", priority: 10 },
  { name: "Hopper", website: "https://hopper.com", priority: 10 },
  { name: "Humi", website: "https://humi.ca", careersPage: "https://humi.ca/careers", priority: 10 },
  { name: "Ideal", website: "https://ideal.com", careersPage: "https://ideal.com/careers/" },
  { name: "Index Exchange", website: "https://indexexchange.com", careersPage: "https://www.indexexchange.com/careers/" },
  { name: "Influitive", website: "https://influitive.com", careersPage: "https://influitive.com/careers/" },
  { name: "InteraXon", website: "https://choosemuse.com", careersPage: "https://www.choosemuse.com/careers" },
  { name: "iQmetrix", website: "https://iqmetrix.com", careersPage: "https://www.iqmetrix.com/careers" },
  { name: "Jane", website: "https://jane.app", priority: 10 },
  { name: "Jobber", website: "https://getjobber.com", priority: 10 },
  { name: "Kinaxis", website: "https://kinaxis.com", careersPage: "https://www.kinaxis.com/en/about/kinaxis-careers/" },
  { name: "Kira Systems", website: "https://kirasystems.com", careersPage: "https://www.kirasystems.com/careers/" },
  { name: "Klue", website: "https://klue.com", priority: 10 },
  { name: "Knix", website: "https://knix.com" },
  { name: "KOHO", website: "https://koho.ca", priority: 10 },
  { name: "LANDR Audio", website: "https://landr.com", careersPage: "https://www.landr.com/careers" },
  { name: "Later", website: "https://later.com" },
  { name: "League", website: "https://league.com", priority: 10 },
  { name: "LemFi", website: "https://lemfi.com", careersPage: "https://www.lemfi.com/careers" },
  { name: "Lightspeed", website: "https://lightspeedhq.com", priority: 10 },
  { name: "Local Logic", website: "https://locallogic.co", careersPage: "https://www.locallogic.co/careers" },
  { name: "Loopio", website: "https://loopio.com" },
  { name: "Lumen5", website: "https://lumen5.com" },
  { name: "Maple", website: "https://getmaple.ca" },
  { name: "Mappedin", website: "https://mappedin.com" },
  { name: "MDA Space", website: "https://mda.space", careersPage: "https://mda.space/careers" },
  { name: "Medella Health", website: "https://medella.ca" },
  { name: "MedMe", website: "https://medmehealth.com" },
  { name: "Mejuri", website: "https://mejuri.com" },
  { name: "Miovision", website: "https://miovision.com" },
  { name: "Mogo", website: "https://mogo.ca" },
  { name: "Moment Energy", website: "https://momentenergy.com", careersPage: "https://momentenergy.com/careers", priority: 10 },
  { name: "Moonvalley", website: "https://moonvalley.ai", careersPage: "https://moonvalley.ai/careers" },
  { name: "Neo Financial", website: "https://neofinancial.com", priority: 10 },
  { name: "Nesto", website: "https://nesto.ca", priority: 10 },
  { name: "Newton", website: "https://newton.co" },
  { name: "North One", website: "https://northone.com" },
  { name: "Notch", website: "https://notchfinancial.com" },
  { name: "Nulogy", website: "https://nulogy.com", careersPage: "https://nulogy.com/about/careers/" },
  { name: "Nuvei", website: "https://nuvei.com", careersPage: "https://nuvei.com/company/careers/" },
  { name: "Nymi", website: "https://nymi.com" },
  { name: "OneVest", website: "https://onevest.com", priority: 10 },
  { name: "Opencare", website: "https://opencare.com", careersPage: "https://www.opencare.com/careers" },
  { name: "OpenText", website: "https://opentext.com", careersPage: "https://www.opentext.com/about/careers" },
  { name: "Panda Hub", website: "https://pandahub.com" },
  { name: "Passage", website: "https://passage.com" },
  { name: "PathFactory", website: "https://pathfactory.com", careersPage: "https://pathfactory.com/careers" },
  { name: "Pela", website: "https://pela.earth", careersPage: "https://pela.earth/pages/careers" },
  { name: "Pelmorex", website: "https://pelmorex.com", careersPage: "https://www.pelmorex.com/en/careers" },
  { name: "PheedLoop", website: "https://pheedloop.com" },
  { name: "Pine", website: "https://pine.ca" },
  { name: "Plooto", website: "https://plooto.com" },
  { name: "Plum", website: "https://plum.io" },
  { name: "PocketHealth", website: "https://pockethealth.com", priority: 10 },
  { name: "Poka", website: "https://poka.io", careersPage: "https://poka.io/en/careers", priority: 10 },
  { name: "PointClickCare", website: "https://pointclickcare.com" },
  { name: "PolicyMe", website: "https://policyme.com", careersPage: "https://www.policyme.com/careers/" },
  { name: "Practice Better", website: "https://practicebetter.io" },
  { name: "Prodigy", website: "https://prodigygame.com", careersPage: "https://www.prodigygame.com/jobs/" },
  { name: "Properly", website: "https://properly.ca" },
  { name: "ProteinQure", website: "https://proteinqure.com", careersPage: "https://www.proteinqure.com/careers.html" },
  { name: "Q4", website: "https://q4inc.com" },
  { name: "Rakuten Kobo", website: "https://kobo.com", careersPage: "https://www.kobo.com/ca/en/p/careers" },
  { name: "Relay", website: "https://relayfi.com", priority: 10 },
  { name: "Resolver", website: "https://resolver.com", careersPage: "https://www.resolver.com/careers" },
  { name: "Rewind", website: "https://rewind.com" },
  { name: "Rise People", website: "https://risepeople.com" },
  { name: "Ritual", website: "https://ritual.co" },
  { name: "Roadmunk", website: "https://roadmunk.com", careersPage: "https://roadmunk.com/careers/jobs" },
  { name: "Rose Rocket", website: "https://roserocket.com" },
  { name: "Sanctuary AI", website: "https://sanctuary.ai" },
  { name: "Sensibill", website: "https://getsensibill.com", careersPage: "https://getsensibill.com/careers" },
  { name: "Shakepay", website: "https://shakepay.com", priority: 10 },
  { name: "Sheertex", website: "https://sheertex.com" },
  { name: "Shopify", website: "https://shopify.com", priority: 20, notes: "Large but still high-signal Canadian tech employer." },
  { name: "Skip the Dishes", website: "https://skipthedishes.com", careersPage: "https://www.skipthedishes.com/jobs" },
  { name: "Smile CDR", website: "https://smilecdr.com" },
  { name: "Smile Digital Health", website: "https://smiledigitalhealth.com" },
  { name: "SnapTravel", website: "https://snaptravel.com", careersPage: "https://www.snaptravel.com/careers" },
  { name: "Snapcommerce", website: "https://snapcommerce.com" },
  { name: "Sortable", website: "https://sortable.com", careersPage: "https://sortable.com/careers/" },
  { name: "SPORTLOGiQ", website: "https://sportlogiq.com", careersPage: "https://sportlogiq.com/careers" },
  { name: "StackAdapt", website: "https://stackadapt.com", priority: 10 },
  { name: "Statflo", website: "https://statflo.com", careersPage: "https://statflo.com/company/careers" },
  { name: "Street Contxt", website: "https://streetcontxt.com", careersPage: "https://streetcontxt.com/careers" },
  { name: "Structura Biotechnology", website: "https://structura.bio", careersPage: "https://structura.bio/#careers" },
  { name: "Svante", website: "https://svanteinc.com" },
  { name: "Symend", website: "https://symend.com" },
  { name: "Synctera", website: "https://synctera.com" },
  { name: "Taplytics", website: "https://taplytics.com", careersPage: "https://taplytics.com/careers/" },
  { name: "Tealbook", website: "https://tealbook.com", careersPage: "https://tealbook.com/careers/" },
  { name: "Tenstorrent", website: "https://tenstorrent.com" },
  { name: "theScore", website: "https://thescore.com", careersPage: "https://www.thescore.com/careers" },
  { name: "ThinkData Works", website: "https://thinkdataworks.com", careersPage: "https://www.thinkdataworks.com/careers" },
  { name: "Thinkific", website: "https://thinkific.com", priority: 10 },
  { name: "ThinkOn", website: "https://thinkon.com" },
  { name: "Top Hat", website: "https://tophat.com", priority: 10 },
  { name: "TouchBistro", website: "https://touchbistro.com", priority: 10 },
  { name: "Trulioo", website: "https://trulioo.com" },
  { name: "Trusscore", website: "https://trusscore.com", careersPage: "https://trusscore.com/company/careers.html", priority: 10 },
  { name: "Tucows", website: "https://tucows.com", careersPage: "https://www.tucows.com/careers/" },
  { name: "Tulip Retail", website: "https://tulip.com", careersPage: "https://tulip.com/about/careers/" },
  { name: "Uberflip", website: "https://uberflip.com", careersPage: "https://www.uberflip.com/careers/" },
  { name: "Unbounce", website: "https://unbounce.com", priority: 10 },
  { name: "Unito", website: "https://unito.io", priority: 10 },
  { name: "Valsoft", website: "https://valsoftcorp.com", careersPage: "https://valsoftcorp.com/careers/" },
  { name: "Vena Solutions", website: "https://venasolutions.com" },
  { name: "Vendasta", website: "https://vendasta.com", careersPage: "https://www.vendasta.com/careers" },
  { name: "VendorPM", website: "https://vendorpm.com" },
  { name: "Veritree", website: "https://veritree.com", priority: 10 },
  { name: "Vetster", website: "https://vetster.com" },
  { name: "Viafoura", website: "https://viafoura.com", careersPage: "https://viafoura.com/careers/" },
  { name: "Vidyard", website: "https://vidyard.com", priority: 10 },
  { name: "Visier", website: "https://visier.com", careersPage: "https://www.visier.com/about/careers/" },
  { name: "Waabi", website: "https://waabi.ai", priority: 10 },
  { name: "Wattpad", website: "https://wattpad.com", careersPage: "https://company.wattpad.com/work-at-wattpad" },
  { name: "Wave", website: "https://waveapps.com", careersPage: "https://www.waveapps.com/about-us/jobs/" },
  { name: "Wealthica", website: "https://wealthica.com" },
  { name: "Wealthsimple", website: "https://wealthsimple.com", priority: 10 },
  { name: "Xanadu", website: "https://xanadu.ai", priority: 10 },
  { name: "Zafin", website: "https://zafin.com" },
  { name: "Zensurance", website: "https://zensurance.com", priority: 10 },
];
