export interface OrganizationSeedConfig {
  name: string;
  website: string;
  priority?: number;
  notes?: string;
}

export const DEFAULT_ORGANIZATIONS: OrganizationSeedConfig[] = [
  { name: "1Password", website: "https://1password.com", priority: 10 },
  { name: "A Thinking Ape", website: "https://athinkingape.com" },
  { name: "Ada", website: "https://ada.cx", priority: 10 },
  { name: "Alert Labs", website: "https://alertlabs.com", priority: 10 },
  { name: "AlayaCare", website: "https://alayacare.com" },
  { name: "ApplyBoard", website: "https://applyboard.com", priority: 10 },
  { name: "Arteria AI", website: "https://arteria.ai" },
  { name: "Attabotics", website: "https://attabotics.com" },
  { name: "Auvik", website: "https://auvik.com" },
  { name: "Axonify", website: "https://axonify.com" },
  { name: "BenchSci", website: "https://benchsci.com", priority: 10 },
  { name: "BetterSleep", website: "https://bettersleep.com" },
  { name: "BlueDot", website: "https://bluedot.global" },
  { name: "Bold Commerce", website: "https://boldcommerce.com" },
  { name: "Borrowell", website: "https://borrowell.com", priority: 10 },
  { name: "Brim Financial", website: "https://brimfinancial.com" },
  { name: "CarbonCure", website: "https://carboncure.com" },
  { name: "Carbonhound", website: "https://carbonhound.io" },
  { name: "Certn", website: "https://certn.co" },
  { name: "ChopValue", website: "https://chopvalue.com" },
  { name: "Clio", website: "https://clio.com", priority: 10 },
  { name: "Clearco", website: "https://clear.co", priority: 10 },
  { name: "ClearEstate", website: "https://clearestate.com", priority: 10 },
  { name: "Cohere", website: "https://cohere.com", priority: 10 },
  { name: "Coinsquare", website: "https://coinsquare.com" },
  { name: "Coveo", website: "https://coveo.com" },
  { name: "D2L", website: "https://d2l.com" },
  { name: "Dapper Labs", website: "https://dapperlabs.com" },
  { name: "Deep Genomics", website: "https://deepgenomics.com" },
  { name: "Dialogue", website: "https://dialogue.co", priority: 10 },
  { name: "Dozr", website: "https://dozr.com" },
  { name: "Drop", website: "https://joindrop.com" },
  { name: "ecobee", website: "https://ecobee.com", priority: 10 },
  { name: "EventMobi", website: "https://eventmobi.com" },
  { name: "Fellow", website: "https://fellow.app" },
  { name: "Flashfood", website: "https://flashfood.com" },
  { name: "Flinks", website: "https://flinks.com" },
  { name: "Float", website: "https://floatfinancial.com", priority: 10 },
  { name: "Forma.ai", website: "https://forma.ai" },
  { name: "FreshBooks", website: "https://freshbooks.com", priority: 10 },
  { name: "Fullscript", website: "https://fullscript.com", priority: 10 },
  { name: "General Fusion", website: "https://generalfusion.com" },
  { name: "GeoComply", website: "https://geocomply.com" },
  { name: "Helcim", website: "https://helcim.com" },
  { name: "Hootsuite", website: "https://hootsuite.com", priority: 10 },
  { name: "Hopper", website: "https://hopper.com", priority: 10 },
  { name: "Jane", website: "https://jane.app", priority: 10 },
  { name: "Jobber", website: "https://getjobber.com", priority: 10 },
  { name: "Klue", website: "https://klue.com", priority: 10 },
  { name: "Knix", website: "https://knix.com" },
  { name: "KOHO", website: "https://koho.ca", priority: 10 },
  { name: "Later", website: "https://later.com" },
  { name: "League", website: "https://league.com", priority: 10 },
  { name: "Lightspeed", website: "https://lightspeedhq.com", priority: 10 },
  { name: "Loopio", website: "https://loopio.com" },
  { name: "Lumen5", website: "https://lumen5.com" },
  { name: "Maple", website: "https://getmaple.ca" },
  { name: "Mappedin", website: "https://mappedin.com" },
  { name: "MedMe", website: "https://medmehealth.com" },
  { name: "Mejuri", website: "https://mejuri.com" },
  { name: "Miovision", website: "https://miovision.com" },
  { name: "Mogo", website: "https://mogo.ca" },
  { name: "Neo Financial", website: "https://neofinancial.com", priority: 10 },
  { name: "Newton", website: "https://newton.co" },
  { name: "Nesto", website: "https://nesto.ca", priority: 10 },
  { name: "North One", website: "https://northone.com" },
  { name: "Notch", website: "https://notchfinancial.com" },
  { name: "Nymi", website: "https://nymi.com" },
  { name: "OneVest", website: "https://onevest.com", priority: 10 },
  { name: "Panda Hub", website: "https://pandahub.com" },
  { name: "Passage", website: "https://passage.com" },
  { name: "PheedLoop", website: "https://pheedloop.com" },
  { name: "Plooto", website: "https://plooto.com" },
  { name: "Plum", website: "https://plum.io" },
  { name: "PocketHealth", website: "https://pockethealth.com", priority: 10 },
  { name: "PointClickCare", website: "https://pointclickcare.com" },
  { name: "Practice Better", website: "https://practicebetter.io" },
  { name: "Properly", website: "https://properly.ca" },
  { name: "Q4", website: "https://q4inc.com" },
  { name: "Relay", website: "https://relayfi.com", priority: 10 },
  { name: "Rewind", website: "https://rewind.com" },
  { name: "Rise People", website: "https://risepeople.com" },
  { name: "Ritual", website: "https://ritual.co" },
  { name: "Rose Rocket", website: "https://roserocket.com" },
  { name: "Sanctuary AI", website: "https://sanctuary.ai" },
  { name: "Shakepay", website: "https://shakepay.com", priority: 10 },
  { name: "Sheertex", website: "https://sheertex.com" },
  { name: "Shopify", website: "https://shopify.com", priority: 20, notes: "Large but still high-signal Canadian tech employer." },
  { name: "Smile CDR", website: "https://smilecdr.com" },
  { name: "Smile Digital Health", website: "https://smiledigitalhealth.com" },
  { name: "Snapcommerce", website: "https://snapcommerce.com" },
  { name: "StackAdapt", website: "https://stackadapt.com", priority: 10 },
  { name: "Svante", website: "https://svanteinc.com" },
  { name: "Symend", website: "https://symend.com" },
  { name: "Tenstorrent", website: "https://tenstorrent.com" },
  { name: "Thinkific", website: "https://thinkific.com", priority: 10 },
  { name: "ThinkOn", website: "https://thinkon.com" },
  { name: "Top Hat", website: "https://tophat.com", priority: 10 },
  { name: "TouchBistro", website: "https://touchbistro.com", priority: 10 },
  { name: "Trulioo", website: "https://trulioo.com" },
  { name: "Unbounce", website: "https://unbounce.com", priority: 10 },
  { name: "Unito", website: "https://unito.io", priority: 10 },
  { name: "Vena Solutions", website: "https://venasolutions.com" },
  { name: "VendorPM", website: "https://vendorpm.com" },
  { name: "Veritree", website: "https://veritree.com", priority: 10 },
  { name: "Vetster", website: "https://vetster.com" },
  { name: "Vidyard", website: "https://vidyard.com", priority: 10 },
  { name: "Waabi", website: "https://waabi.ai", priority: 10 },
  { name: "Wealthica", website: "https://wealthica.com" },
  { name: "Wealthsimple", website: "https://wealthsimple.com", priority: 10 },
  { name: "Xanadu", website: "https://xanadu.ai", priority: 10 },
  { name: "Zafin", website: "https://zafin.com" },
  { name: "Zensurance", website: "https://zensurance.com", priority: 10 },
];
